/* This is the starter code for the substance program for the tutorial
 * that teaches functions in Penrose. Follow along with the write-up. 
 * Good luck! :)
 */
 
VectorSpace U
Vector w
Vector v
In(w, U)
In(v,U)
/**************YOUR CODE - START********************/


Vector u := AddV(w, v)
In(u, U)

/**************YOUR CODE - END**********************/

AutoLabel All /* leave this as the last line */
